package com.cucumber.stepdefinitions;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

public class Locators

{
	
	// QA TEST DATA loading from Test_Data Properties file
	
	
	public static String QA_PORTAL_d;
	public static String QA_User_d;
	public static String QA_pwd_wr_d;
	public static String QA_pwd_d;
	public static String QA_PORTAL_DDash_d;
	public static String QA_QC_PORTAL_d;
	public static String QA_QC_Operator_name_d;
	public static String QA_QC_TC_d;
	public static String QA_QC_Eml_id_d;
	public static String QA_QC_LD_d;
	

	
	
	// Locating XPATH from Elements_Xpath Properties test file
	
	public static String QA_Username_x;
	public static String QA_Cont_x;
	public static String QA_pwd_x; 
	public static String QA_log_x;
	public static String QA_Invalid_alert_x;
	
	public static String Cont_btn_x;
	public static String Pwd_x;
	public static String Login_btn_x;
	public static String Default_role_x; 
	public static String SNP_Role_x; 
	public static String Default_Chnl_x;
	public static String Test_Chnl_x;
	public static String SANDP_PROGRAMS_tab_x; 
	public static String Program_Asset_x; 
	public static String SNP_Prog_Dt_x;
	public static String SNP_Prog_Dt_yestr_x;
	public static String OnAirPromo;
	public static String Pr_Dash_Create_x;
	public static String Pr_Excl_Camp_x;
	public static String Pr_Camp_Tx_x;
	public static String Pr_Excl_save_x;
	public static String Pr_Excl_sav_alrt_x;
	public static String Pr_Typ_nam_x;
	public static String Pr_Typ_nam_alrt_x;
	public static String Pr_Tm_nam_x;
	public static String Pr_Tm_nam_alrt_x;
	public static String Pr_Excl_Pr_fr_x;
	public static String Pr_Excl_Pr_fr2_x;
	public static String Pr_Excl_Scroll_x;
	public static String Roleslist_x;
	public static String Dft_Dsh_x;
	public static String QA_Logout_x;
	public static String Pr_Excl_Promo_Type_x;
	public static String Pr_Excl_Promo_Type2_x;
	public static String Pr_Excl_Chnl_x;
	public static String Pr_Excl_Shw_nm_x;
	public static String Pr_Excl_Pr_Cr_x;
	public static String Pr_Excl_Chnl_dt_x;
	public static String Pr_Excl_Chnl_tab_x;
	public static String SNP_Re_Com_x;
	public static String SNP_All_Com_x;
	public static String SNP_Apr_Hist_x;
	public static String Plyr_Stp_x; 
	public static String Plyr_Prv_Frm_x; 
	public static String Plyr_Nxt_Frm_x;
	public static String Plyr_Pause_x;
	public static String Plyr_Seek_x;
	public static String Plyr_Prv_Sec_x;
	public static String Plyr_Nxt_Sec_x;
	public static String Plyr_Fst_Fwd_x;
	public static String Plyr_Ply_Slw_x;
	public static String Plyr_Ply_Vol_icn_x;
	public static String Plyr_Ply_Vol_Level_x;
	public static String Plyr_Hlp_x;
	public static String Plyr_Hlp_popup_Okbtn_x;
	public static String Plyr_Settings_icon_x;
	public static String Plyr_Quality_dd_x;
	public static String Plyr_Quality_dd_hide_x;
	public static String Plyr_Full_Src_x;
	public static String Plyr_Rv_Mrkin_Src_x;
	public static String Plyr_Rv_Stp_x; 
	public static String Plyr_Rv_Prv_Frm_x; 
	public static String Plyr_Rv_Nxt_Frm_x;
	public static String Plyr_Rv_Pause_x;
	public static String Plyr_Rv_Seek_x;
	public static String Plyr_Rv_Prv_Sec_x;
	public static String Plyr_Rv_Nxt_Sec_x;
	public static String Plyr_Rv_Fst_Fwd_x;
	public static String Plyr_Rv_Ply_Slw_x;
	public static String Plyr_Rv_Ply_Vol_icn_x;
	public static String Plyr_Rv_Ply_Vol_Level_x;
	public static String Plyr_Rv_Hlp_x;
	public static String Plyr_Rv_Hlp_popup_Okbtn_x;
	public static String Plyr_Rv_Settings_icon_x;
	public static String Plyr_Rv_Quality_dd_x;
	public static String Plyr_Rv_Quality_dd_hide_x;
	public static String Plyr_Rv_Full_Src_x;
	public static String Plyr_Rv_Mrkout_Src_x;
	public static String Add_Seg_sav_x;
	public static String Add_Seg_wo_cmt_alrt_x;
	public static String Add_Seg_wt_cmt_x;
	public static String Plyr_Rv_BR_lst_x;
	public static String Plyr_RV_Sts_x;
	public static String Plyr_Sbt_x;
	
	public static String Prg_tab_x;
	public static String Prg_crt_map_x;
	public static String Prg_map_x;
	public static String Prg_map_qc_x;
	public static String Prg_asset_ttl_x;
	public static String Asst_AuditT_tab_x;
	public static String Asst_Close_x;
	public static String Asst_CFN_x;
	public static String QA_QC_Username_x;
	public static String QA_QC_Cont_x;
	public static String QA_QC_pwd_x;
	public static String QA_QC_log_x;
	public static String QC_search_fld_x;
	public static String QC_search_btn_x;
	public static String QC_Asst_entry_x;
	public static String QC_popup_x;
	public static String QC_save_btn_x;
	public static String QC_Fr_Rt_x;
	public static String QC_Sgmt_tab_x;
	public static String QC_Frt_Sgmt_ty_x;
	public static String QC_Frt_Sgmt_tcin_x;
	public static String QC_Frt_Sgmt_tcout_x;
	public static String QC_Sgmt_Add_x;
	public static String QC_Sgmt_tbl_x;
	public static String QC_fr_fld_x;
	public static String QC_Sgmt_Dis_x;
	public static String QC_Sgmt_tci1_x;
	public static String QC_Sgmt_tco1_x;
	public static String QC_Frt_Sgmt_ini_x;
	public static String QC_tab_x;
	public static String QC_oprt_x;
	public static String QC_oprt2_x;
	public static String QC_Sts_x;
	public static String QC_Sts_ps_x;
	public static String QC_Aud_Ld_x;
	public static String QC_Rsl_x;
	public static String QC_Cr_Sz_x;
	public static String QC_Email_Ch_x;
	public static String QC_Email_Id_x;
	public static String QC_Yes_x;
	public static String QC_logout_x;
	public static String QC_Srt_TC_x;
	public static String QC_Das_Sub_Sts_x;
	public static String QC_CFN_x;
	
	public static String Search_Icon_x;
	public static String Search_Text_x;
	public static String Search_Button_x;
	public static String Search_Lang_x;
	public static String Search_Lang_srcfld_x;
	public static String Search_Lang_srcfld2_x;
	public static String Search_Lang_chbx_x;
	public static String Search_1st_Asst_x;
	public static String Search_Lang_chbx2_x;
	public static String Search_scroll_x;
	public static String Eng_Clr_x;
	public static String Eng_Clr2_x;
	public static String Search_Lang_Hindi_x;
	public static String Search_Lang_Hin2_x;
	public static String Search_Lang_Kannada_x;
	public static String Search_Lang_Marathi_x;
	public static String Search_Lang_Bengali_x;
	public static String Search_Lang_French_x;
	public static String Search_Lang_German_x;
	public static String Search_Lang_Japanese_x;
	public static String Search_Refflt_Qlt_x;
	public static String Search_Refflt_QltHD_x;
	public static String Search_Refflt_QltSD_x;
	public static String Search_Refflt_QltOth_x;		 
	public static String Search_Refflt_HD_Asst_x;
	public static String Search_Refflt_SD_Asst_x;
	public static String Search_Refflt_Othr_Asst_x;
	public static String Search_Refflt_UpldDT_x;
	public static String Asst_Lib_RF_Vr_scrool_x;
	public static String Asst_Lib_CT_x;
	public static String Search_Refflt_Arc_x;
	public static String Asst_Lib_RF_PLO_x;
	public static String Asst_Lib_RF_SSS_x;
	public static String Asst_Lib_RF_Lang_sr_x;
	public static String Asst_1st_Arc_x;
	public static String Asst_Lib_RF_Arc_Chx_x;
	public static String Lib_Asst_Cnt_x;
	public static String Lib_Asst_total_x;
	public static String Asst_Lib_RF_NonArch_x;
	public static String Asst_Lib_RF_NtArc_Chx_x;
	public static String Lib_NonArch_Cnt_x; 
	public static String Asst_Lib_RF_CtSt_x;
	public static String Lib_NonCat_Cnt_x;
	public static String Asst_Lib_RF_CtSt_Chx_x;
	public static String Asst_Lib_RF_CtSt_UnChx_x;
	public static String Asst_Lib_RF_PLO_Asg_Chx_x;
	public static String Asst_Lib_RF_PLO_NAsg_Chx_x;
	public static String Asst_1st_Asg_x;
	public static String Lib_PLO_St_x;
	public static String Lib_NonAsg_Cnt_x;
	public static String Asst_Lib_RF_SS_Chx_x;
	public static String Asst_Lib_RF_SS_UnChx_x;
	public static String Lib_NonSS_Cnt_x;
	public static String Lib_TotalNS_Cnt_x;
	public static String CT_Program_x;
	public static String CT_Promo_x;
	public static String CT_RC_x;
	public static String CT_Songs_x;
	public static String CT_TVC_x;
	public static String CT_Programs_Display_x;
	public static String Show_more_x;
	public static String CT_Clip_check_box_x;
	public static String CT_Movie_UnCheck_box_x;
	public static String Update_LM_DD_x;
	public static String Update_LM_BOX_ID_x;
	public static String Update_LM_Title_x;
	public static String Update_LM_Segments_x;
	public static String Update_Logical_Medai_dd_x;
	public static String Update_Duration_x;
	public static String Update_click_x;
	public static String CT_Clip_UnCheck_x;
	public static String CT_Clips_Display_x;
	public static String CT_Movie_Check_box_x;
	public static String CT_Movies_Display_x;
	public static String BMSTemplatization_x;
	public static String Create_Temaplate_x;
	public static String BMSTemplatization_tab_x;
	public static String Template_Name_x;
	public static String Group_Name_x;
	public static String Add_Segment_Temp_x;
	public static String Random_Group_Name_x;
	public static String Group_name_Temp_x2;
	public static String Cancel_btn_x;
	public static String Group_name_dd_x;
	public static String TCin_TCout_11;
	public static String TCin_TCout_12;
	public static String TCin_TCout_21;
	public static String TCin_TCout_22;
	public static String TCin_TCout_31;
	public static String TCin_TCout_32;
	public static String select_x;
	public static String select_x2;
	public static String Save_btn_x;
	public static String Temp_D_Search_x;
	public static String BMS_Temp_D_search_x;
	public static String Movie_AuditT_tab_x;
	public static String CT_Movie_CFN_x;
	public static String Movie_Close_AuditT_tab_x;
	public static String CT_Sponsors_x;
	public static String Upload_Status_x;
	public static String Upd_srt_Dt;
	public static String Upd_end_Dt;
	public static String Apply_btn_x;
	public static String Strt_Date_inpt_x;
	public static String End_Date_inpt_x;
	public static String Caldr_popup_x;
	public static String Caldr_Tdy_x;
	public static String Caldr_Prvyr_x;
	public static String Caldr_Prvmnt_x;
	public static String Caldr_Nxtmnt_x;
	public static String Caldr_Nxtyr_x;
	public static String Frm_dt_err_x;
	public static String Caldr_Prmnt_1stday_x;
	public static String To_dt_err_x;
	public static String Caldr_Today_x;
	public static String Caldr_pop_up_x;
	public static String Caldr_Nxtmnt2_x;
	public static String Caldr_Prmnt_1stday2_x;
	public static String Caldr_1stday_x;
	public static String Caldr_Prv_Mnt_x;
	public static String Caldr_Today2_x;
	public static String Upld_From_dt_x;
	public static String Upld_To_dt_x;
	public static String Upld_fct_x;
	public static String Fct_x;
	public static String Caldr_1stdat_x;
	public static String Upld_dat_1stast_x;
	public static String Upld_dat_1stastdsc_x;
	public static String Srt_by_x;
	public static String Srt_byAsc_x;
	public static String Srt_byttlDsc_x;
	public static String Srt_byttlAsc_x;
	public static String Asset_1st_Ttl_x;
	public static String Add_Seg_x;
	public static String Rev_Sub_x;
	public static String Rev_Stat_x;
	
	
	public static void getlocators() throws IOException {

		// Create FileInputStream Object for test data
		FileInputStream fileInput = new FileInputStream(new File("D:\\STAR_QA\\src\\test\\resources\\Data\\Star_Testdata.properties"));

		// Create Properties object
		Properties prop = new Properties();

		//Loading Data from Test_Data Properties test file
		prop.load(fileInput);

		QA_PORTAL_d = prop.getProperty("QA_PORTAL_d");
		QA_User_d = prop.getProperty("QA_User_d");
		QA_pwd_wr_d = prop.getProperty("QA_pwd_wr_d");
		QA_pwd_d = prop.getProperty("QA_pwd_d");
		QA_PORTAL_DDash_d = prop.getProperty("QA_PORTAL_DDash_d");
		QA_QC_PORTAL_d  = prop.getProperty("QA_QC_PORTAL_d");
		QA_QC_Operator_name_d = prop.getProperty("QA_QC_Operator_name_d");
		QA_QC_TC_d = prop.getProperty("QA_QC_TC_d");
		QA_QC_Eml_id_d = prop.getProperty("QA_QC_Eml_id_d");
		QA_QC_LD_d  = prop.getProperty("QA_QC_LD_d");
		

		// Create FileInputStream Object for XPATH VALUES 
		
		FileInputStream Inputxpath = new FileInputStream(new File("D:\\STAR_QA\\src\\test\\resources\\Data\\Xpath.properties"));

		// Create Properties object
		Properties prop1 = new Properties();

		// // loading XPATH from Elements_Xpath Properties test file
		prop1.load(Inputxpath);

		QA_Username_x = prop1.getProperty("QA_Username_x");
		QA_Cont_x = prop1.getProperty("QA_Cont_x");
		QA_pwd_x = prop1.getProperty("QA_pwd_x"); 
		QA_log_x = prop1.getProperty("QA_log_x");
		QA_Invalid_alert_x = prop1.getProperty("QA_Invalid_alert_x");
		Cont_btn_x = prop1.getProperty("Cont_btn_x");
		 Pwd_x = prop1.getProperty("Pwd_x");
		 Login_btn_x = prop1.getProperty("Login_btn_x");
		 Default_role_x = prop1.getProperty("Default_role_x"); 
		 SNP_Role_x = prop1.getProperty("SNP_Role_x"); 
		 Default_Chnl_x = prop1.getProperty("Default_Chnl_x");
		 Test_Chnl_x = prop1.getProperty("Test_Chnl_x");
		 SANDP_PROGRAMS_tab_x = prop1.getProperty("SANDP_PROGRAMS_tab_x"); 
		 Program_Asset_x = prop1.getProperty("Program_Asset_x");
		 SNP_Prog_Dt_x = prop1.getProperty("SNP_Prog_Dt_x");
		 SNP_Prog_Dt_yestr_x = prop1.getProperty("SNP_Prog_Dt_yestr_x");
		 OnAirPromo = prop1.getProperty("OnAirPromo");
		 Pr_Dash_Create_x = prop1.getProperty("Pr_Dash_Create_x");
		 Pr_Excl_Camp_x = prop1.getProperty("Pr_Excl_Camp_x");
		 Pr_Camp_Tx_x = prop1.getProperty("Pr_Camp_Tx_x");
		 Pr_Excl_save_x = prop1.getProperty("Pr_Excl_save_x");
		 Pr_Excl_sav_alrt_x = prop1.getProperty("Pr_Excl_sav_alrt_x");
		 Pr_Typ_nam_x = prop1.getProperty("Pr_Typ_nam_x");
		 Pr_Typ_nam_alrt_x = prop1.getProperty("Pr_Typ_nam_alrt_x");
		 Pr_Tm_nam_x = prop1.getProperty("Pr_Tm_nam_x");
		 Pr_Tm_nam_alrt_x = prop1.getProperty("Pr_Tm_nam_alrt_x");
		 Pr_Excl_Pr_fr_x = prop1.getProperty("Pr_Excl_Pr_fr_x");
		 Pr_Excl_Pr_fr2_x = prop1.getProperty("Pr_Excl_Pr_fr2_x");
		 Pr_Excl_Scroll_x = prop1.getProperty("Pr_Excl_Scroll_x");
		 Roleslist_x = prop1.getProperty("Roleslist_x");
		 Dft_Dsh_x = prop1.getProperty("Dft_Dsh_x"); 
		 QA_Logout_x = prop1.getProperty("QA_Logout_x");
		 Pr_Excl_Promo_Type_x = prop1.getProperty("Pr_Excl_Promo_Type_x");
		 Pr_Excl_Promo_Type2_x = prop1.getProperty("Pr_Excl_Promo_Type2_x");
		 Pr_Excl_Chnl_x = prop1.getProperty("Pr_Excl_Chnl_x");
		 Pr_Excl_Shw_nm_x = prop1.getProperty("Pr_Excl_Shw_nm_x");
		 Pr_Excl_Pr_Cr_x = prop1.getProperty("Pr_Excl_Pr_Cr_x");
		 Pr_Excl_Chnl_dt_x = prop1.getProperty("Pr_Excl_Chnl_dt_x");
		 Pr_Excl_Chnl_tab_x = prop1.getProperty("Pr_Excl_Chnl_tab_x");
		 SNP_Re_Com_x = prop1.getProperty("SNP_Re_Com_x"); 
		 SNP_All_Com_x = prop1.getProperty("SNP_All_Com_x");
		 SNP_Apr_Hist_x = prop1.getProperty("SNP_Apr_Hist_x");
		 Prg_tab_x = prop1.getProperty("Prg_tab_x");
		 Prg_crt_map_x = prop1.getProperty("Prg_crt_map_x");
		 Prg_map_x = prop1.getProperty("Prg_map_x");
		 Prg_map_qc_x = prop1.getProperty("Prg_map_qc_x");
		 Prg_asset_ttl_x = prop1.getProperty("Prg_asset_ttl_x");
		 Asst_AuditT_tab_x = prop1.getProperty("Asst_AuditT_tab_x");
		 Asst_Close_x = prop1.getProperty("Asst_Close_x");
		 Asst_CFN_x = prop1.getProperty("Asst_CFN_x");
		 QA_QC_Username_x = prop1.getProperty("QA_QC_Username_x");
		 QA_QC_Cont_x = prop1.getProperty("QA_QC_Cont_x");
		 QA_QC_pwd_x  = prop1.getProperty("QA_QC_pwd_x");
		 QA_QC_log_x = prop1.getProperty("QA_QC_log_x");
		 QC_search_fld_x = prop1.getProperty("QC_search_fld_x");
		 QC_search_btn_x = prop1.getProperty("QC_search_btn_x");
		 QC_Asst_entry_x = prop1.getProperty("QC_Asst_entry_x");
		 QC_popup_x = prop1.getProperty("QC_Asst_entry_x");
		 QC_save_btn_x = prop1.getProperty("QC_save_btn_x");
		 QC_Fr_Rt_x = prop1.getProperty("QC_Fr_Rt_x");
		 QC_Sgmt_tab_x = prop1.getProperty("QC_Sgmt_tab_x");
		 QC_Frt_Sgmt_ini_x = prop1.getProperty("QC_Frt_Sgmt_ini_x");
		 QC_Frt_Sgmt_ty_x = prop1.getProperty("QC_Frt_Sgmt_ty_x");
		 QC_Frt_Sgmt_tcin_x = prop1.getProperty("QC_Frt_Sgmt_tcin_x");
		 QC_Frt_Sgmt_tcout_x = prop1.getProperty("QC_Frt_Sgmt_tcout_x");
		 QC_Sgmt_Add_x = prop1.getProperty("QC_Sgmt_Add_x");
		 QC_Sgmt_tbl_x = prop1.getProperty("QC_Sgmt_tbl_x");
		 QC_fr_fld_x = prop1.getProperty("QC_fr_fld_x");
		 QC_Sgmt_Dis_x = prop1.getProperty("QC_Sgmt_Dis_x");
		 QC_Sgmt_tci1_x = prop1.getProperty("QC_Sgmt_tci1_x");
		 QC_Sgmt_tco1_x = prop1.getProperty("QC_Sgmt_tco1_x");
		 QC_tab_x = prop1.getProperty("QC_tab_x");
		 QC_oprt_x = prop1.getProperty("QC_oprt_x");
		 QC_oprt2_x = prop1.getProperty("QC_oprt2_x");
		 QC_Sts_x = prop1.getProperty("QC_Sts_x");
		 QC_Sts_ps_x = prop1.getProperty("QC_Sts_ps_x");
		 QC_Aud_Ld_x = prop1.getProperty("QC_Aud_Ld_x");
		 QC_Rsl_x  = prop1.getProperty("QC_Rsl_x");
		 QC_Cr_Sz_x = prop1.getProperty("QC_Cr_Sz_x");
		 QC_Email_Ch_x = prop1.getProperty("QC_Email_Ch_x");
		 QC_Email_Id_x = prop1.getProperty("QC_Email_Id_x");
		 QC_Yes_x = prop1.getProperty("QC_Yes_x");
		 QC_logout_x = prop1.getProperty("QC_logout_x");
		 QC_Srt_TC_x = prop1.getProperty("QC_Srt_TC_x");
		 QC_Das_Sub_Sts_x = prop1.getProperty("QC_Das_Sub_Sts_x");
		 QC_CFN_x = prop1.getProperty("QC_CFN_x");
		 Plyr_Rv_Pause_x = prop1.getProperty("Plyr_Rv_Pause_x");
		 Plyr_Rv_Seek_x = prop1.getProperty("Plyr_Rv_Seek_x");
		 Plyr_Rv_Pause_x = prop1.getProperty("Plyr_Rv_Pause_x");
		 Plyr_Rv_Stp_x = prop1.getProperty("Plyr_Rv_Stp_x");
		 Plyr_Rv_Pause_x = prop1.getProperty("Plyr_Rv_Pause_x");
		 Plyr_Rv_Prv_Frm_x = prop1.getProperty("Plyr_Rv_Prv_Frm_x");
		 Plyr_Rv_Nxt_Frm_x = prop1.getProperty("Plyr_Rv_Nxt_Frm_x");
		 Plyr_Rv_Prv_Sec_x = prop1.getProperty("Plyr_Rv_Prv_Sec_x");
		 Plyr_Rv_Nxt_Sec_x = prop1.getProperty("Plyr_Rv_Nxt_Sec_x");
		 Plyr_Rv_Pause_x = prop1.getProperty("Plyr_Rv_Pause_x");
		 Plyr_Rv_Ply_Slw_x = prop1.getProperty("Plyr_Rv_Ply_Slw_x");
		 Plyr_Rv_Fst_Fwd_x = prop1.getProperty("Plyr_Rv_Fst_Fwd_x");
		 Plyr_Rv_Ply_Slw_x = prop1.getProperty("Plyr_Rv_Ply_Slw_x");
		 Plyr_Rv_Ply_Vol_icn_x = prop1.getProperty("Plyr_Rv_Ply_Vol_icn_x");
		 Plyr_Rv_Settings_icon_x = prop1.getProperty("Plyr_Rv_Settings_icon_x");
		 Plyr_Rv_Ply_Vol_Level_x = prop1.getProperty("Plyr_Rv_Ply_Vol_Level_x");
		 Plyr_Rv_Hlp_x = prop1.getProperty("Plyr_Rv_Hlp_x");
		 Plyr_Rv_Hlp_popup_Okbtn_x = prop1.getProperty("Plyr_Rv_Hlp_popup_Okbtn_x");
		 Plyr_Rv_Quality_dd_x = prop1.getProperty("Plyr_Rv_Quality_dd_x");
		 Plyr_Rv_Quality_dd_hide_x = prop1.getProperty("Plyr_Rv_Quality_dd_hide_x");
		 Plyr_Rv_Mrkin_Src_x = prop1.getProperty("Plyr_Rv_Mrkin_Src_x");
		 Plyr_Rv_Mrkout_Src_x = prop1.getProperty("Plyr_Rv_Mrkout_Src_x");
		 Add_Seg_sav_x = prop1.getProperty("Add_Seg_sav_x");
		 Add_Seg_wo_cmt_alrt_x = prop1.getProperty("Add_Seg_wo_cmt_alrt_x");
		 Add_Seg_wt_cmt_x = prop1.getProperty("Add_Seg_wt_cmt_x");
		 Plyr_Rv_BR_lst_x = prop1.getProperty("Plyr_Rv_BR_lst_x");
		 Plyr_RV_Sts_x = prop1.getProperty("Plyr_RV_Sts_x");
		 Plyr_Sbt_x  = prop1.getProperty("Plyr_Sbt_x");
		 Search_Icon_x = prop1.getProperty("Search_Icon_x");
		 Search_Text_x = prop1.getProperty("Search_Text_x");
		 Search_Button_x = prop1.getProperty("Search_Button_x");
		 Search_Lang_x = prop1.getProperty("Search_Lang_x");
		 Search_Lang_chbx_x = prop1.getProperty("Search_Lang_chbx_x");
		 Search_1st_Asst_x = prop1.getProperty("Search_1st_Asst_x");
		 Search_Lang_srcfld_x = prop1.getProperty("Search_Lang_srcfld_x");
		 Search_Lang_srcfld2_x = prop1.getProperty("Search_Lang_srcfld2_x");
		 Search_Lang_chbx2_x = prop1.getProperty("Search_Lang_chbx2_x");
		 Search_scroll_x = prop1.getProperty("Search_scroll_x");
		 Eng_Clr_x = prop1.getProperty("Eng_Clr_x");
		 Eng_Clr2_x = prop1.getProperty("Eng_Clr2_x");
		 Search_Lang_Kannada_x = prop1.getProperty("Search_Lang_Kannada_x");
		 Search_Lang_Hindi_x = prop1.getProperty("Search_Lang_Hindi_x");
		 Search_Lang_Marathi_x = prop1.getProperty("Search_Lang_Marathi_x");
		 Search_Lang_Bengali_x = prop1.getProperty("Search_Lang_Bengali_x");
		 Search_Lang_French_x = prop1.getProperty("Search_Lang_French_x");
		 Search_Lang_German_x = prop1.getProperty("Search_Lang_German_x");
		 Search_Lang_Japanese_x = prop1.getProperty("Search_Lang_Japanese_x");
		 Search_Lang_Hin2_x = prop1.getProperty("Search_Lang_Hin2_x");
		 Search_Refflt_Qlt_x = prop1.getProperty("Search_Refflt_Qlt_x");
		 Search_Refflt_QltHD_x = prop1.getProperty("Search_Refflt_QltHD_x");
		 Search_Refflt_QltSD_x = prop1.getProperty("Search_Refflt_QltSD_x");
		 Search_Refflt_QltOth_x = prop1.getProperty("Search_Refflt_QltOth_x");		 
		 Search_Refflt_HD_Asst_x = prop1.getProperty("Search_Refflt_HD_Asst_x");
		 Search_Refflt_Othr_Asst_x = prop1.getProperty("Search_Refflt_Othr_Asst_x");
		 Search_Refflt_SD_Asst_x = prop1.getProperty("Search_Refflt_SD_Asst_x");
		 Search_Refflt_UpldDT_x = prop1.getProperty("Search_Refflt_UpldDT_x");
		 Asst_Lib_RF_Vr_scrool_x = prop1.getProperty("Asst_Lib_RF_Vr_scrool_x");
		 Asst_Lib_CT_x = prop1.getProperty("Asst_Lib_CT_x");
		 Search_Refflt_Arc_x = prop1.getProperty("Search_Refflt_Arc_x");
		 Asst_Lib_RF_PLO_x = prop1.getProperty("Asst_Lib_RF_PLO_x");
		 Asst_Lib_RF_SSS_x = prop1.getProperty("Asst_Lib_RF_SSS_x");
		 Asst_Lib_RF_Lang_sr_x = prop1.getProperty("Asst_Lib_RF_Lang_sr_x");
		 Asst_1st_Arc_x = prop1.getProperty("Asst_1st_Arc_x");
		 Asst_Lib_RF_Arc_Chx_x = prop1.getProperty("Asst_Lib_RF_Arc_Chx_x");
		 Lib_Asst_Cnt_x = prop1.getProperty("Lib_Asst_Cnt_x");
		 Lib_Asst_total_x  = prop1.getProperty("Lib_Asst_Cnt_x");
		 Asst_Lib_RF_NonArch_x = prop1.getProperty("Asst_Lib_RF_NonArch_x");
		 Asst_Lib_RF_NtArc_Chx_x = prop1.getProperty("Asst_Lib_RF_NtArc_Chx_x");
		 Lib_NonArch_Cnt_x = prop1.getProperty("Lib_NonArch_Cnt_x");
		 Asst_Lib_RF_CtSt_x = prop1.getProperty("Asst_Lib_RF_CtSt_x");
		 Lib_NonCat_Cnt_x = prop1.getProperty("Lib_NonCat_Cnt_x");
		 Asst_Lib_RF_CtSt_Chx_x = prop1.getProperty("Asst_Lib_RF_CtSt_Chx_x");
		 Asst_Lib_RF_CtSt_UnChx_x = prop1.getProperty("Asst_Lib_RF_CtSt_UnChx_x");
		 Asst_Lib_RF_PLO_Asg_Chx_x = prop1.getProperty("Asst_Lib_RF_PLO_Asg_Chx_x");
		 Asst_Lib_RF_PLO_NAsg_Chx_x = prop1.getProperty("Asst_Lib_RF_PLO_NAsg_Chx_x");
		 Asst_1st_Asg_x = prop1.getProperty("Asst_1st_Asg_x");
		 Lib_PLO_St_x = prop1.getProperty("Lib_PLO_St_x");
		 Lib_NonAsg_Cnt_x = prop1.getProperty("Lib_NonAsg_Cnt_x");
		 Asst_Lib_RF_SS_Chx_x = prop1.getProperty("Asst_Lib_RF_SS_Chx_x");
		 Asst_Lib_RF_SS_UnChx_x = prop1.getProperty("Asst_Lib_RF_SS_UnChx_x");;
		 Lib_NonSS_Cnt_x = prop1.getProperty("Lib_NonSS_Cnt_x");
		 Lib_TotalNS_Cnt_x = prop1.getProperty("Lib_TotalNS_Cnt_x");
		 CT_Program_x = prop1.getProperty("CT_Program_x");
		 CT_Promo_x = prop1.getProperty("CT_Promo_x");
		 CT_RC_x = prop1.getProperty("CT_RC_x");
		 CT_Songs_x = prop1.getProperty("CT_Songs_x");
		 CT_TVC_x = prop1.getProperty("CT_TVC_x");
		 CT_Sponsors_x= prop1.getProperty("CT_Sponsors_x");
         CT_Programs_Display_x = prop1.getProperty("CT_Programs_Display_x");
         CT_Clip_check_box_x = prop1.getProperty("CT_Clip_check_box_x");
         Show_more_x = prop1.getProperty("Show_more_x");
         CT_Movie_UnCheck_box_x = prop1.getProperty("CT_Movie_UnCheck_box_x");
         Update_LM_DD_x = prop1.getProperty("Update_LM_DD_x");
 		Update_LM_BOX_ID_x = prop1.getProperty("Update_LM_BOX_ID_x");
 		Update_LM_Title_x = prop1.getProperty("Update_LM_Title_x");
 		Update_LM_Segments_x = prop1.getProperty("Update_LM_Segments_x");
 		Update_Logical_Medai_dd_x = prop1.getProperty("Update_Logical_Medai_dd_x");
 		Update_Duration_x = prop1.getProperty("Update_Duration_x");
 		Update_click_x  = prop1.getProperty("Update_click_x");
 		CT_Clip_UnCheck_x = prop1.getProperty("CT_Clip_UnCheck_x");
 		CT_Movie_Check_box_x = prop1.getProperty("CT_Movie_Check_box_x");
 		CT_Movie_UnCheck_box_x = prop1.getProperty("CT_Movie_UnCheck_box_x");
 		CT_Clips_Display_x = prop1.getProperty("CT_Clips_Display_x");
 		CT_Movies_Display_x = prop1.getProperty("CT_Movies_Display_x");
 		BMSTemplatization_x = prop1.getProperty("BMSTemplatization_x");
 		Create_Temaplate_x =  prop1.getProperty("Create_Temaplate_x");
 		BMSTemplatization_tab_x = prop1.getProperty("BMSTemplatization_tab_x");
 		Template_Name_x = prop1.getProperty("Template_Name_x");
 		Group_Name_x = prop1.getProperty("Group_Name_x");
 		Add_Segment_Temp_x = prop1.getProperty("Add_Segment_Temp_x");
 		Random_Group_Name_x = prop1.getProperty("Random_Group_Name_x");
 		Group_name_Temp_x2 = prop1.getProperty("Group_name_Temp_x2");
 		Cancel_btn_x = prop1.getProperty("Cancel_btn_x");
 		Group_name_dd_x = prop1.getProperty("Group_name_dd_x");
 		TCin_TCout_11  = prop1.getProperty("TCin_TCout_11");
 		TCin_TCout_12  = prop1.getProperty("TCin_TCout_12");
 		TCin_TCout_21  = prop1.getProperty("TCin_TCout_21");
 		TCin_TCout_22  = prop1.getProperty("TCin_TCout_22");
 		TCin_TCout_31  = prop1.getProperty("TCin_TCout_31");
 		TCin_TCout_32  = prop1.getProperty("TCin_TCout_32");
 		select_x = prop1.getProperty("select_x");
 		select_x2 = prop1.getProperty("select_x2");
 		Save_btn_x = prop1.getProperty("Save_btn_x");
 		Temp_D_Search_x = prop1.getProperty("Temp_D_Search_x");
 		BMS_Temp_D_search_x = prop1.getProperty("BMS_Temp_D_search_x");
 		Show_more_x = prop1.getProperty("Show_more_x");
 		Movie_AuditT_tab_x = prop1.getProperty("Movie_AuditT_tab_x");
 		CT_Movie_CFN_x = prop1.getProperty("CT_Movie_CFN_x");
 		Movie_Close_AuditT_tab_x =  prop1.getProperty("Movie_Close_AuditT_tab_x");
 		Upload_Status_x =  prop1.getProperty("Upload_Status_x");
 		Upd_srt_Dt =  prop1.getProperty("Upd_srt_Dt");
 		Upd_end_Dt =  prop1.getProperty("Upd_end_Dt");
 		Apply_btn_x =  prop1.getProperty("Apply_btn_x");
 		Strt_Date_inpt_x =  prop1.getProperty("Strt_Date_inpt_x");
 		End_Date_inpt_x =  prop1.getProperty("End_Date_inpt_x");
 		Caldr_popup_x =  prop1.getProperty("Caldr_popup_x");
 		Caldr_Tdy_x =  prop1.getProperty("Caldr_Tdy_x");
 		Caldr_Prvyr_x =  prop1.getProperty("Caldr_Prvyr_x");
 		Caldr_Prvmnt_x =  prop1.getProperty("Caldr_Prvmnt_x");
 		Caldr_Nxtmnt_x =  prop1.getProperty("Caldr_Nxtmnt_x");
 		Caldr_Nxtyr_x =  prop1.getProperty("Caldr_Nxtyr_x");
 		Frm_dt_err_x =  prop1.getProperty("Frm_dt_err_x");
 		Caldr_Prmnt_1stday_x =  prop1.getProperty("Caldr_Prmnt_1stday_x");
 		To_dt_err_x =  prop1.getProperty("To_dt_err_x");
 		Caldr_Today_x =  prop1.getProperty("Caldr_Today_x");
 		Caldr_pop_up_x =  prop1.getProperty("Caldr_pop_up_x");
 		Caldr_Nxtmnt2_x =  prop1.getProperty("Caldr_Nxtmnt2_x");
 		Caldr_1stday_x =  prop1.getProperty("Caldr_1stday_x");
 		Caldr_Prmnt_1stday2_x =  prop1.getProperty("Caldr_Prmnt_1stday2_x");
 		Caldr_Prv_Mnt_x =  prop1.getProperty("Caldr_Prv_Mnt_x");
 		Caldr_Today2_x =  prop1.getProperty("Caldr_Today2_x");
 		Upld_To_dt_x =  prop1.getProperty("Upld_To_dt_x");
 		Upld_From_dt_x = prop1.getProperty("Upld_From_dt_x");
 		Upld_fct_x = prop1.getProperty("Upld_fct_x");
 		Fct_x = prop1.getProperty("Fct_x");
 		Caldr_1stdat_x = prop1.getProperty("Caldr_1stdat_x");
 		Upld_dat_1stast_x = prop1.getProperty("Upld_dat_1stast_x");
 		Srt_by_x = prop1.getProperty("Srt_by_x");
 		Srt_byAsc_x = prop1.getProperty("Srt_byAsc_x");
 		Srt_byttlAsc_x = prop1.getProperty("Srt_byttlAsc_x");
 		Srt_byttlDsc_x = prop1.getProperty("Srt_byttlDsc_x");
 		Asset_1st_Ttl_x = prop1.getProperty("Asset_1st_Ttl_x");
 		Upld_dat_1stastdsc_x = prop1.getProperty("Upld_dat_1stastdsc_x");
 		Add_Seg_x = prop1.getProperty("Add_Seg_x");
 		Rev_Sub_x = prop1.getProperty("Rev_Sub_x");
 		Rev_Stat_x = prop1.getProperty("Rev_Stat_x");
		}

}
